name: FKickAll
api: 4.0.0
main: FRashkar\KickAllPlayers\Loader
version: 1.0.0
author: FRashkar-pm

commands:
  kickall:
    description: FKick All Commands
    permission: fkickall.use
    aliases:
    - fk
permissions:
  kickall.use:
    default: op
