name: FKickAll
api: [4.0.0, 5.0.0]
main: FRashkar\KickAllPlayers\Loader
version: 1.0.1
author: FRashkar-pm

commands:
  fkickall:
    description: FKick All Commands
    permission: fkickall.use
    aliases:
      - fk
permissions:
  fkickall.use:
    default: op
